### ISSUE TITLE
Setup instructions failing ... How to resolve?

### ISSUE THREAD

**Issue by smchamberlin** [IBM/chaostoolkit-ibm#6]
Not sure if docs need update or I'm doing something wrong, I'm not able to install using pip:

```
(chaostk) stevens-mbp:chaostoolkit-ibm smc2$ pip install -U chaostoolkit-ibmcloud
ERROR: Could not find a version that satisfies the requirement chaostoolkit-ibmcloud (from versions: none)
ERROR: No matching distribution found for chaostoolkit-ibmcloud
WARNING: You are using pip version 21.1.3; however, version 21.3.1 is available.
You should consider upgrading via the '/Users/smc2/.venvs/chaostk/bin/python3 -m pip install --upgrade pip' command.
(chaostk) stevens-mbp:chaostoolkit-ibm smc2$
```

also can't install the pre-reqs for the dev environment:
```
(chaostk) stevens-mbp:chaostoolkit-ibm smc2$ pip --version
pip 21.1.3 from /Users/smc2/.venvs/chaostk/lib/python3.9/site-packages/pip (python 3.9)
(chaostk) stevens-mbp:chaostoolkit-ibm smc2$ pip install -r requirements-dev.txt -r requirements.txt
Collecting coverage
  Downloading coverage-6.2-cp39-cp39-macosx_10_9_x86_64.whl (179 kB)
     |████████████████████████████████| 179 kB 1.4 MB/s 
Collecting pycodestyle
  Downloading pycodestyle-2.8.0-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 2.2 MB/s 
Collecting pytest>=2.8
  Downloading pytest-6.2.5-py3-none-any.whl (280 kB)
     |████████████████████████████████| 280 kB 6.7 MB/s 
Collecting pytest-cov
  Downloading pytest_cov-3.0.0-py3-none-any.whl (20 kB)
Collecting pytest-sugar
  Downloading pytest-sugar-0.9.4.tar.gz (12 kB)
Requirement already satisfied: requests in /Users/smc2/.venvs/chaostk/lib/python3.9/site-packages (from -r requirements-dev.txt (line 6)) (2.26.0)
Collecting requests_mock
  Downloading requests_mock-1.9.3-py2.py3-none-any.whl (27 kB)
Collecting ibm-vpc==0.7.0
  Downloading ibm-vpc-0.7.0.tar.gz (212 kB)
     |████████████████████████████████| 212 kB 31.1 MB/s 
Collecting jsonpath2==0.4.4
  Downloading jsonpath2-0.4.4-py3-none-any.whl (34 kB)
Collecting logzero==1.5.0
  Downloading logzero-1.5.0-py2.py3-none-any.whl (14 kB)
Collecting paramiko==2.7.2
  Downloading paramiko-2.7.2-py2.py3-none-any.whl (206 kB)
     |████████████████████████████████| 206 kB 20.1 MB/s 
Collecting ibm_platform_services==0.19.1
  Downloading ibm-platform-services-0.19.1.tar.gz (216 kB)
     |████████████████████████████████| 216 kB 25.0 MB/s 
Collecting ibm-cloud-sdk-core==3.10.1
  Downloading ibm-cloud-sdk-core-3.10.1.tar.gz (40 kB)
     |████████████████████████████████| 40 kB 14.1 MB/s 
Collecting mysql-connector-python~=8.0.23
  Downloading mysql_connector_python-8.0.27-py2.py3-none-any.whl (341 kB)
     |████████████████████████████████| 341 kB 19.2 MB/s 
Collecting py~=1.10.0
  Downloading py-1.10.0-py2.py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 13.6 MB/s 
Collecting colorama~=0.4.4
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting cryptography~=3.4.6
  Downloading cryptography-3.4.8-cp36-abi3-macosx_10_10_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 20.7 MB/s 
Collecting wheel~=0.36.2
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting attrs~=20.3.0
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 13.1 MB/s 
Collecting six~=1.15.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting PyJWT~=2.0.1
  Downloading PyJWT-2.0.1-py3-none-any.whl (15 kB)
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 18.9 MB/s 
Collecting toml~=0.10.2
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: PyYAML~=5.4.1 in /Users/smc2/.venvs/chaostk/lib/python3.9/site-packages (from -r requirements.txt (line 18)) (5.4.1)
Collecting pluggy~=0.13.1
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting iniconfig~=1.1.1
  Downloading iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting atomicwrites~=1.4.0
  Using cached atomicwrites-1.4.0-py2.py3-none-any.whl (6.8 kB)
Collecting numpy~=1.20.1
  Downloading numpy-1.20.3-cp39-cp39-macosx_10_9_x86_64.whl (16.1 MB)
     |████████████████████████████████| 16.1 MB 1.1 MB/s 
Collecting certifi~=2020.12.5
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 29.7 MB/s 
Collecting chardet~=4.0.0
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 33.3 MB/s 
Requirement already satisfied: urllib3~=1.26.3 in /Users/smc2/.venvs/chaostk/lib/python3.9/site-packages (from -r requirements.txt (line 25)) (1.26.7)
Collecting coverage
  Downloading coverage-5.5-cp39-cp39-macosx_10_9_x86_64.whl (207 kB)
     |████████████████████████████████| 207 kB 37.7 MB/s 
Collecting python-dateutil~=2.8.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting bcrypt~=3.2.0
  Downloading bcrypt-3.2.0-cp36-abi3-macosx_10_9_x86_64.whl (31 kB)
Collecting idna~=2.10
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting pyparsing~=2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting pycparser~=2.20
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 37.3 MB/s 
Collecting websocket-client~=0.48.0
  Downloading websocket_client-0.48.0-py2.py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 28.0 MB/s 
Collecting setuptools~=40.8.0
  Downloading setuptools-40.8.0-py2.py3-none-any.whl (575 kB)
     |████████████████████████████████| 575 kB 24.2 MB/s 
Collecting click~=7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting chaostoolkit~=1.9.0
  Downloading chaostoolkit-1.9.6-py2.py3-none-any.whl (19 kB)
Collecting packaging~=20.9
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 14.6 MB/s 
Collecting termcolor~=1.1.0
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
Collecting zipp~=3.4.0
  Downloading zipp-3.4.2-py3-none-any.whl (5.3 kB)
Collecting pymqi~=1.12.0
  Downloading pymqi-1.12.0.tar.gz (75 kB)
     |████████████████████████████████| 75 kB 11.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/smc2/.venvs/chaostk/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s4/cr5tk5s150j8t4362bbmp6s40000gp/T/pip-install-59dy79i4/pymqi_cd9419ba7c284ec79c28feee1ea4b677/setup.py'"'"'; __file__='"'"'/private/var/folders/s4/cr5tk5s150j8t4362bbmp6s40000gp/T/pip-install-59dy79i4/pymqi_cd9419ba7c284ec79c28feee1ea4b677/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/s4/cr5tk5s150j8t4362bbmp6s40000gp/T/pip-pip-egg-info-a3430w3d
         cwd: /private/var/folders/s4/cr5tk5s150j8t4362bbmp6s40000gp/T/pip-install-59dy79i4/pymqi_cd9419ba7c284ec79c28feee1ea4b677/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s4/cr5tk5s150j8t4362bbmp6s40000gp/T/pip-install-59dy79i4/pymqi_cd9419ba7c284ec79c28feee1ea4b677/setup.py", line 165, in <module>
        raise Exception('MQ libraries could not be found')
    Exception: MQ libraries could not be found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/55/33/c567a624e7c09a5ab50352dc2aa586fbdf75fbe185d55a2d1d027fe685b2/pymqi-1.12.0.tar.gz#sha256=ca18659242f34ff3484b454fd872036a87b285c214e0907353c815e12e46cb75 (from https://pypi.org/simple/pymqi/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pymqi~=1.12.0 (from versions: 1.0.1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.5.2, 1.5.3, 1.5.4, 1.7.0, 1.7.1, 1.7.2, 1.7.2.post1, 1.8.0, 1.9.0, 1.9.0.post1, 1.9.1, 1.9.2, 1.9.3, 1.10, 1.10.1, 1.11.0, 1.11.1, 1.12.0)
ERROR: No matching distribution found for pymqi~=1.12.0
WARNING: You are using pip version 21.1.3; however, version 21.3.1 is available.
You should consider upgrading via the '/Users/smc2/.venvs/chaostk/bin/python3 -m pip install --upgrade pip' command.
(chaostk) stevens-mbp:chaostoolkit-ibm smc2$ 
```

**Comment by smchamberlin** [comment]
Also tried pip 21.3.1:
```
(chaostk) stevens-mbp:chaostoolkit-ibm smc2$ pip --version
pip 21.3.1 from /Users/smc2/.venvs/chaostk/lib/python3.9/site-packages/pip (python 3.9)
(chaostk) stevens-mbp:chaostoolkit-ibm smc2$ pip install -U chaostoolkit-ibmcloud
ERROR: Could not find a version that satisfies the requirement chaostoolkit-ibmcloud (from versions: none)
ERROR: No matching distribution found for chaostoolkit-ibmcloud
(chaostk) stevens-mbp:chaostoolkit-ibm smc2$ 
```

**Comment by ahmadsayed** [comment]
@smchamberlin I believe  library expected to have mq client per-installed https://dsuch.github.io/pymqi/#installation , I suggest to try the following 
1 - Install MQ client on your machine
2 - pip3 install pymqi 

if it resolved will update the documentation , or make this components optional, MQ is mainly to test MQ only it does not impact any other functionalities, 

Unfortunately, since I left IBM I do not  have an access to IBM Cloud environment, or IBM tools  to debug from my side.

but if you want to dig deeper from your side, you try to  remove pymqi from the requirements, and remove the  this probe 
https://github.com/IBM/chaostoolkit-ibm/blob/main/ibmcloud/middleware/probes.py
it should be safe as far you are not going to run any mq probes

**Comment by smchamberlin** [comment]
Thanks @ahmadsayed - I was able to build the dev environment after installing the MQ client for Mac from here: https://developer.ibm.com/tutorials/mq-macos-dev/

So, `pip install -r requirements-dev.txt -r requirements.txt` works but I still can't get `pip install -U chaostoolkit-ibmcloud` to work:

```
(chaostk) stevens-mbp:~ smc2$ pip install -U chaostoolkit-ibmcloud
ERROR: Could not find a version that satisfies the requirement chaostoolkit-ibmcloud (from versions: none)
ERROR: No matching distribution found for chaostoolkit-ibmcloud
(chaostk) stevens-mbp:~ smc2$ 
```

**Comment by ahmadsayed** [comment]
@smchamberlin  I do not recall that I published this package yet to Pypi to be able to be index for PIP, we were  still  in kind of early phase,  as of now, you can  use via linking it 
```
pip install -e .
```

https://github.com/IBM/chaostoolkit-ibm#develop

**Comment by ahmadsayed** [comment]
@smchamberlin please feel free to reach out to me directly on my [linkedin](https://www.linkedin.com/in/ahmed-sayed-7791a717/) , if you need a  deeper dive in this driver.

**Comment by smchamberlin** [comment]
Thank you @ahmadsayed - I am able to start using the IBM extensions after your instructions.

Unfortunately I'm not able to message you on LinkedIn unless I am a premium member.  Maybe if you add me I could message you? https://www.linkedin.com/in/stevenmchamberlin/

Currently I am getting 404 "instance not found" error when I try to stop a server node, I suspect maybe my service_url endpoint may not be set correctly, where/how can I verify what this value should be for my VPC?  Thank you.
